// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SwoledBrosBE.Models;

#nullable disable

namespace SwoledBrosBE.Models.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SwoledBrosBE.Models.FitnessApp.Models.DietPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BreakfastId")
                        .HasColumnType("integer");

                    b.Property<int?>("BrunchSnackId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DinnerId")
                        .HasColumnType("integer");

                    b.Property<int?>("EveningSnackId")
                        .HasColumnType("integer");

                    b.Property<int?>("LunchId")
                        .HasColumnType("integer");

                    b.Property<int?>("PreBedSnackId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BreakfastId");

                    b.HasIndex("BrunchSnackId");

                    b.HasIndex("DinnerId");

                    b.HasIndex("EveningSnackId");

                    b.HasIndex("LunchId");

                    b.HasIndex("PreBedSnackId");

                    b.HasIndex("UserId");

                    b.ToTable("DietPlans");
                });

            modelBuilder.Entity("SwoledBrosBE.Models.FitnessApp.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("SwoledBrosBE.Models.FitnessApp.Models.MealItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FoodName")
                        .HasColumnType("text");

                    b.Property<int?>("MealId")
                        .HasColumnType("integer");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.ToTable("MealItems");
                });

            modelBuilder.Entity("SwoledBrosBE.Models.FitnessApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Height")
                        .HasColumnType("double precision");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SwoledBrosBE.Models.FitnessApp.Models.WorkoutExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExerciseName")
                        .HasColumnType("text");

                    b.Property<int?>("Reps")
                        .HasColumnType("integer");

                    b.Property<int?>("Sets")
                        .HasColumnType("integer");

                    b.Property<int?>("WorkoutSplitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutSplitId");

                    b.ToTable("WorkoutExercises");
                });

            modelBuilder.Entity("SwoledBrosBE.Models.FitnessApp.Models.WorkoutSplit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Day")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WorkoutSplits");
                });

            modelBuilder.Entity("SwoledBrosBE.Models.FitnessApp.Models.DietPlan", b =>
                {
                    b.HasOne("SwoledBrosBE.Models.FitnessApp.Models.Meal", "Breakfast")
                        .WithMany()
                        .HasForeignKey("BreakfastId");

                    b.HasOne("SwoledBrosBE.Models.FitnessApp.Models.Meal", "BrunchSnack")
                        .WithMany()
                        .HasForeignKey("BrunchSnackId");

                    b.HasOne("SwoledBrosBE.Models.FitnessApp.Models.Meal", "Dinner")
                        .WithMany()
                        .HasForeignKey("DinnerId");

                    b.HasOne("SwoledBrosBE.Models.FitnessApp.Models.Meal", "EveningSnack")
                        .WithMany()
                        .HasForeignKey("EveningSnackId");

                    b.HasOne("SwoledBrosBE.Models.FitnessApp.Models.Meal", "Lunch")
                        .WithMany()
                        .HasForeignKey("LunchId");

                    b.HasOne("SwoledBrosBE.Models.FitnessApp.Models.Meal", "PreBedSnack")
                        .WithMany()
                        .HasForeignKey("PreBedSnackId");

                    b.HasOne("SwoledBrosBE.Models.FitnessApp.Models.User", "User")
                        .WithMany("DietPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Breakfast");

                    b.Navigation("BrunchSnack");

                    b.Navigation("Dinner");

                    b.Navigation("EveningSnack");

                    b.Navigation("Lunch");

                    b.Navigation("PreBedSnack");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SwoledBrosBE.Models.FitnessApp.Models.MealItem", b =>
                {
                    b.HasOne("SwoledBrosBE.Models.FitnessApp.Models.Meal", null)
                        .WithMany("Items")
                        .HasForeignKey("MealId");
                });

            modelBuilder.Entity("SwoledBrosBE.Models.FitnessApp.Models.WorkoutExercise", b =>
                {
                    b.HasOne("SwoledBrosBE.Models.FitnessApp.Models.WorkoutSplit", null)
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutSplitId");
                });

            modelBuilder.Entity("SwoledBrosBE.Models.FitnessApp.Models.WorkoutSplit", b =>
                {
                    b.HasOne("SwoledBrosBE.Models.FitnessApp.Models.User", "User")
                        .WithMany("WorkoutSplits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SwoledBrosBE.Models.FitnessApp.Models.Meal", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SwoledBrosBE.Models.FitnessApp.Models.User", b =>
                {
                    b.Navigation("DietPlans");

                    b.Navigation("WorkoutSplits");
                });

            modelBuilder.Entity("SwoledBrosBE.Models.FitnessApp.Models.WorkoutSplit", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
